name: 'pull-request'

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb
        env:
          MARIADB_ROOT_PASSWORD: dijon
          MARIADB_DATABASE: dijon
          MARIADB_USER: dijon
          MARIADB_PASSWORD: dijon
        ports:
          - 33306:3306
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
