name: 'pull-request'

on:
  pull_request:
    branches: [ 'main' ]

jobs:
#  tests:
#    runs-on: ubuntu-latest
#    services:
#      mariadb:
#        image: mariadb:latest
#        ports:
#          - 3306
#        env:
#          MYSQL_USER: dijon
#          MYSQL_PASSWORD: dijon
#          MYSQL_DATABASE: dijon
#          MYSQL_ROOT_PASSWORD: dijon
#        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
#
#    steps:
#      - uses: actions/checkout@v1
#
#      - name: Verify MariaDB connection
#        env:
#          DBPORT: ${{ job.services.mariadb.ports[3306] }}
#        run: |
#          while ! mysqladmin ping -h"127.0.0.1" -P"$DBPORT" --silent; do
#            sleep 1
#          done
#
#      - name: Set up Python 3.9
#        uses: actions/setup-python@v1
#        with:
#          python-version: 3.9
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install poetry
#          poetry install
#      - name: Run Tests
#        env:
#          DYNACONF_DBPORT: ${{ job.services.mariadb.ports[3306] }}
#        run: |
#          make test
  build:
    runs-on: ubuntu-latest
    container:
      image: 'gcr.io/kaniko-project/executor:debug'
    name: Build image
    steps:
      - name: Build image
        run: |
          pwd
          ls -a
          mkdir -p /kaniko/.docker
          echo "{\"credsStore\":\"ecr-login\"}" > /kaniko/.docker/config.json
          /kaniko/executor \
            --context=/__w/testthethings/testthethings \
            --dockerfile=Dockerfile \
            --destination dijon:mustard \
            --no-push
